[package]
name = "ferna/roblox-luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

Janitor = "howmanysmall/janitor@1.18.3"
Networker = "leifstout/networker@0.3.0"
Signal = "sleitnick/signal@2.0.3"
Sift = "csqrl/sift@0.0.11"
FastCastRedux = "encodedvenom/fastcastredux@0.1.3"

[server-dependencies]

ProfileStore = "lm-loleris/profilestore@1.0.3"