[package]
name = "ferna/roblox-luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

Signal = "sleitnick/signal@2.0.3"
Promise = "evaera/promise@4.0.0"
Ripple = "littensy/ripple@0.10.0"
Jecs = "ukendio/jecs@0.10.0"
Vide = "alicesaidhi/vide@0.4.0"
Vide-Ripple = "littensy/vide-ripple@0.10.2"
Charm = "littensy/charm@0.10.0"
Confetti = "sqzee1/confetti@2.0.2"
Janitor = "howmanysmall/janitor@1.18.3"
Lync = "axp3cter/lync@2.1.2"
QuickZone = "ldgerrits/quickzone@1.3.187"

[server-dependencies]

ProfileStore = "lm-loleris/profilestore@1.0.3"