[package]
name = "ferna/roblox-luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

signal = "sleitnick/signal@2.0.3"
promise = "evaera/promise@4.0.0"
ripple = "littensy/ripple@0.10.0"
jecs = "ukendio/jecs@0.11.0"
vide = "alicesaidhi/vide@0.4.0"
vide_ripple = "littensy/vide-ripple@0.10.2"
charm = "littensy/charm@0.11.0"
charm_sync = "littensy/charm-sync@0.4.0"
janitor = "howmanysmall/janitor@1.18.3"
quickzone = "ldgerrits/quickzone@1.4.6"
sera = "enzzyfrenzzy/sera@0.0.2"
replecs = "pepeeltoro41/replecs@0.3.1"
jecs-utils = "pepeeltoro41/jecs-utils@1.4.4"
jecs-vide = "pepeeltoro41/jecs-vide@1.0.8"
jabby = "ukendio/jabby@0.2.0"
planck = "yetanotherclown/planck@0.2.0"

[server-dependencies]

profile_store = "lm-loleris/profilestore@1.0.3"
